print('Introduce numero 1:')
num1=int(input())
print('Introduce numero 2:')
num2=int(input())
div=int(num1/num2)
res=int(num1%num2)
print(num1,'entre',num2,'da un cociente de:',div,'y un resto de:',res)