print('introduce el nombre del alumno:')
nombre=input()
print('introduce la nota de la practica1')
p1=int(input())
print('introduce la nota de la practica2')
p2=int(input())
print('introduce la nota de la practica3')
p3=int(input())
print('introduce la nota del examen parcial')
ep=int(input())
print('introduce la nota del examen final')
ef=int(input())
pp=float((p1+p2+p3)/3)
prom=int((pp+2*ep+3*ef)/6)
print('El promedio de',nombre,'es:',prom)